# Generated by Django 3.1.5 on 2021-01-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig_app', '0002_auto_20210117_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='caption',
        ),
    ]
