# Generated by Django 3.1.5 on 2021-01-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig_app', '0003_auto_20210117_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='content',
        ),
    ]
